export default {
	ZONES_RECIEVED: 'ZONES_RECIEVED',
	ZONE_CREATED: 'ZONE_CREATED',
	SELECTED_ZONE: 'SELECTED_ZONE',
	COMMENTS_RECEIVED: 'COMMENTS_RECEIVED',
	COMMENT_CREATED: 'COMMENT_CREATED',
	CURRENT_USER_RECEIVED: 'CURRENT_USER_RECEIVED',
	PROFILE_RECEIVED: 'PROFILE_RECEIVED'
}